// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: ingest.proto

package ingestpb

import (
	coordinatorpb "github.com/Razeefshaik/vectorsearch-gateway/go/proto/coordinatorpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Key     *coordinatorpb.Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Copied from GatewayInsertRequest. The consumer will put this value
	// into the final indexing-result event.
	CorrelationId string `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEvent) Reset() {
	*x = IngestEvent{}
	mi := &file_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEvent) ProtoMessage() {}

func (x *IngestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEvent.ProtoReflect.Descriptor instead.
func (*IngestEvent) Descriptor() ([]byte, []int) {
	return file_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IngestEvent) GetKey() *coordinatorpb.Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *IngestEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IngestEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_ingest_proto protoreflect.FileDescriptor

const file_ingest_proto_rawDesc = "" +
	"\n" +
	"\fingest.proto\x12\x16vectorsearch.ingest.v1\x1a\x11coordinator.proto\"\x82\x01\n" +
	"\vIngestEvent\x122\n" +
	"\x03key\x18\x01 \x01(\v2 .vectorsearch.coordinator.v1.KeyR\x03key\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationIdBHZFgithub.com/Razeefshaik/vectorsearch-gateway/go/proto/ingestpb;ingestpbb\x06proto3"

var (
	file_ingest_proto_rawDescOnce sync.Once
	file_ingest_proto_rawDescData []byte
)

func file_ingest_proto_rawDescGZIP() []byte {
	file_ingest_proto_rawDescOnce.Do(func() {
		file_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)))
	})
	return file_ingest_proto_rawDescData
}

var file_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ingest_proto_goTypes = []any{
	(*IngestEvent)(nil),       // 0: vectorsearch.ingest.v1.IngestEvent
	(*coordinatorpb.Key)(nil), // 1: vectorsearch.coordinator.v1.Key
}
var file_ingest_proto_depIdxs = []int32{
	1, // 0: vectorsearch.ingest.v1.IngestEvent.key:type_name -> vectorsearch.coordinator.v1.Key
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ingest_proto_init() }
func file_ingest_proto_init() {
	if File_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingest_proto_rawDesc), len(file_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ingest_proto_goTypes,
		DependencyIndexes: file_ingest_proto_depIdxs,
		MessageInfos:      file_ingest_proto_msgTypes,
	}.Build()
	File_ingest_proto = out.File
	file_ingest_proto_goTypes = nil
	file_ingest_proto_depIdxs = nil
}
