// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/coordinator.proto

// Public API: client -> coordinator. This is the only service external
// clients ever talk to; ShardService (shard.proto) is internal.

package coordinatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Label         uint64                 `protobuf:"varint,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_proto_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Key) GetLabel() uint64 {
	if x != nil {
		return x.Label
	}
	return 0
}

type ScoredKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredKey) Reset() {
	*x = ScoredKey{}
	mi := &file_proto_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredKey) ProtoMessage() {}

func (x *ScoredKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredKey.ProtoReflect.Descriptor instead.
func (*ScoredKey) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *ScoredKey) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ScoredKey) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *InsertRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *InsertRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{3}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{5}
}

type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query []float32              `protobuf:"fixed32,1,rep,packed,name=query,proto3" json:"query,omitempty"`
	K     uint32                 `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	Ef    uint32                 `protobuf:"varint,3,opt,name=ef,proto3" json:"ef,omitempty"`
	// If false (the default), any shard failure fails the whole search --
	// a partial top-k is not a safe substitute for the true top-k, since the
	// failed shard may have held the actual nearest neighbours. Set true only
	// when availability matters more than completeness for this query.
	AllowPartial  bool `protobuf:"varint,4,opt,name=allow_partial,json=allowPartial,proto3" json:"allow_partial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchRequest) GetEf() uint32 {
	if x != nil {
		return x.Ef
	}
	return 0
}

func (x *SearchRequest) GetAllowPartial() bool {
	if x != nil {
		return x.AllowPartial
	}
	return false
}

type SearchResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Results []*ScoredKey           `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Always populated, even on full success, so degradation is never silent:
	// a caller can log "8/8 shards" on the happy path and immediately notice
	// when it becomes "7/8".
	ShardsQueried uint32 `protobuf:"varint,2,opt,name=shards_queried,json=shardsQueried,proto3" json:"shards_queried,omitempty"`
	ShardsFailed  uint32 `protobuf:"varint,3,opt,name=shards_failed,json=shardsFailed,proto3" json:"shards_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetResults() []*ScoredKey {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetShardsQueried() uint32 {
	if x != nil {
		return x.ShardsQueried
	}
	return 0
}

func (x *SearchResponse) GetShardsFailed() uint32 {
	if x != nil {
		return x.ShardsFailed
	}
	return 0
}

var File_proto_coordinator_proto protoreflect.FileDescriptor

const file_proto_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x17proto/coordinator.proto\x12\x1bvectorsearch.coordinator.v1\"8\n" +
	"\x03Key\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\x04R\x05label\"[\n" +
	"\tScoredKey\x122\n" +
	"\x03key\x18\x01 \x01(\v2 .vectorsearch.coordinator.v1.KeyR\x03key\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\"[\n" +
	"\rInsertRequest\x122\n" +
	"\x03key\x18\x01 \x01(\v2 .vectorsearch.coordinator.v1.KeyR\x03key\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\"\x10\n" +
	"\x0eInsertResponse\"C\n" +
	"\rDeleteRequest\x122\n" +
	"\x03key\x18\x01 \x01(\v2 .vectorsearch.coordinator.v1.KeyR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"h\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x03(\x02R\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\rR\x01k\x12\x0e\n" +
	"\x02ef\x18\x03 \x01(\rR\x02ef\x12#\n" +
	"\rallow_partial\x18\x04 \x01(\bR\fallowPartial\"\x9e\x01\n" +
	"\x0eSearchResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.vectorsearch.coordinator.v1.ScoredKeyR\aresults\x12%\n" +
	"\x0eshards_queried\x18\x02 \x01(\rR\rshardsQueried\x12#\n" +
	"\rshards_failed\x18\x03 \x01(\rR\fshardsFailed2\xb7\x02\n" +
	"\fVectorSearch\x12a\n" +
	"\x06Insert\x12*.vectorsearch.coordinator.v1.InsertRequest\x1a+.vectorsearch.coordinator.v1.InsertResponse\x12a\n" +
	"\x06Delete\x12*.vectorsearch.coordinator.v1.DeleteRequest\x1a+.vectorsearch.coordinator.v1.DeleteResponse\x12a\n" +
	"\x06Search\x12*.vectorsearch.coordinator.v1.SearchRequest\x1a+.vectorsearch.coordinator.v1.SearchResponseBRZPgithub.com/Razeefshaik/vectorsearch-gateway/go/proto/coordinatorpb;coordinatorpbb\x06proto3"

var (
	file_proto_coordinator_proto_rawDescOnce sync.Once
	file_proto_coordinator_proto_rawDescData []byte
)

func file_proto_coordinator_proto_rawDescGZIP() []byte {
	file_proto_coordinator_proto_rawDescOnce.Do(func() {
		file_proto_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)))
	})
	return file_proto_coordinator_proto_rawDescData
}

var file_proto_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_coordinator_proto_goTypes = []any{
	(*Key)(nil),            // 0: vectorsearch.coordinator.v1.Key
	(*ScoredKey)(nil),      // 1: vectorsearch.coordinator.v1.ScoredKey
	(*InsertRequest)(nil),  // 2: vectorsearch.coordinator.v1.InsertRequest
	(*InsertResponse)(nil), // 3: vectorsearch.coordinator.v1.InsertResponse
	(*DeleteRequest)(nil),  // 4: vectorsearch.coordinator.v1.DeleteRequest
	(*DeleteResponse)(nil), // 5: vectorsearch.coordinator.v1.DeleteResponse
	(*SearchRequest)(nil),  // 6: vectorsearch.coordinator.v1.SearchRequest
	(*SearchResponse)(nil), // 7: vectorsearch.coordinator.v1.SearchResponse
}
var file_proto_coordinator_proto_depIdxs = []int32{
	0, // 0: vectorsearch.coordinator.v1.ScoredKey.key:type_name -> vectorsearch.coordinator.v1.Key
	0, // 1: vectorsearch.coordinator.v1.InsertRequest.key:type_name -> vectorsearch.coordinator.v1.Key
	0, // 2: vectorsearch.coordinator.v1.DeleteRequest.key:type_name -> vectorsearch.coordinator.v1.Key
	1, // 3: vectorsearch.coordinator.v1.SearchResponse.results:type_name -> vectorsearch.coordinator.v1.ScoredKey
	2, // 4: vectorsearch.coordinator.v1.VectorSearch.Insert:input_type -> vectorsearch.coordinator.v1.InsertRequest
	4, // 5: vectorsearch.coordinator.v1.VectorSearch.Delete:input_type -> vectorsearch.coordinator.v1.DeleteRequest
	6, // 6: vectorsearch.coordinator.v1.VectorSearch.Search:input_type -> vectorsearch.coordinator.v1.SearchRequest
	3, // 7: vectorsearch.coordinator.v1.VectorSearch.Insert:output_type -> vectorsearch.coordinator.v1.InsertResponse
	5, // 8: vectorsearch.coordinator.v1.VectorSearch.Delete:output_type -> vectorsearch.coordinator.v1.DeleteResponse
	7, // 9: vectorsearch.coordinator.v1.VectorSearch.Search:output_type -> vectorsearch.coordinator.v1.SearchResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_coordinator_proto_init() }
func file_proto_coordinator_proto_init() {
	if File_proto_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coordinator_proto_rawDesc), len(file_proto_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coordinator_proto_goTypes,
		DependencyIndexes: file_proto_coordinator_proto_depIdxs,
		MessageInfos:      file_proto_coordinator_proto_msgTypes,
	}.Build()
	File_proto_coordinator_proto = out.File
	file_proto_coordinator_proto_goTypes = nil
	file_proto_coordinator_proto_depIdxs = nil
}
