// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Label         uint64                 `protobuf:"varint,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayKey) Reset() {
	*x = GatewayKey{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKey) ProtoMessage() {}

func (x *GatewayKey) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKey.ProtoReflect.Descriptor instead.
func (*GatewayKey) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayKey) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GatewayKey) GetLabel() uint64 {
	if x != nil {
		return x.Label
	}
	return 0
}

type GatewayScoredResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *GatewayKey            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayScoredResult) Reset() {
	*x = GatewayScoredResult{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayScoredResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayScoredResult) ProtoMessage() {}

func (x *GatewayScoredResult) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayScoredResult.ProtoReflect.Descriptor instead.
func (*GatewayScoredResult) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayScoredResult) GetKey() *GatewayKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GatewayScoredResult) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type GatewaySearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	K             uint32                 `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	Ef            uint32                 `protobuf:"varint,3,opt,name=ef,proto3" json:"ef,omitempty"`
	AllowPartial  bool                   `protobuf:"varint,4,opt,name=allow_partial,json=allowPartial,proto3" json:"allow_partial,omitempty"`
	ClientId      uint64                 `protobuf:"varint,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewaySearchRequest) Reset() {
	*x = GatewaySearchRequest{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewaySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewaySearchRequest) ProtoMessage() {}

func (x *GatewaySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewaySearchRequest.ProtoReflect.Descriptor instead.
func (*GatewaySearchRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GatewaySearchRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GatewaySearchRequest) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *GatewaySearchRequest) GetEf() uint32 {
	if x != nil {
		return x.Ef
	}
	return 0
}

func (x *GatewaySearchRequest) GetAllowPartial() bool {
	if x != nil {
		return x.AllowPartial
	}
	return false
}

func (x *GatewaySearchRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GatewaySearchResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Results []*GatewayScoredResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Passed through from the coordinator's own SearchResponse so degradation
	// is never silent here either.
	ShardsQueried uint32 `protobuf:"varint,2,opt,name=shards_queried,json=shardsQueried,proto3" json:"shards_queried,omitempty"`
	ShardsFailed  uint32 `protobuf:"varint,3,opt,name=shards_failed,json=shardsFailed,proto3" json:"shards_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewaySearchResponse) Reset() {
	*x = GatewaySearchResponse{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewaySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewaySearchResponse) ProtoMessage() {}

func (x *GatewaySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewaySearchResponse.ProtoReflect.Descriptor instead.
func (*GatewaySearchResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GatewaySearchResponse) GetResults() []*GatewayScoredResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GatewaySearchResponse) GetShardsQueried() uint32 {
	if x != nil {
		return x.ShardsQueried
	}
	return 0
}

func (x *GatewaySearchResponse) GetShardsFailed() uint32 {
	if x != nil {
		return x.ShardsFailed
	}
	return 0
}

type GatewayInsertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   *GatewayKey            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Text  string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Optional caller-generated identifier used to correlate this request
	// with its eventual asynchronous indexing result.
	CorrelationId string `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayInsertRequest) Reset() {
	*x = GatewayInsertRequest{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayInsertRequest) ProtoMessage() {}

func (x *GatewayInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayInsertRequest.ProtoReflect.Descriptor instead.
func (*GatewayInsertRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GatewayInsertRequest) GetKey() *GatewayKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GatewayInsertRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GatewayInsertRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type GatewayInsertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoes the supplied correlation ID. An empty value means the caller
	// did not request asynchronous result correlation.
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayInsertResponse) Reset() {
	*x = GatewayInsertResponse{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayInsertResponse) ProtoMessage() {}

func (x *GatewayInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayInsertResponse.ProtoReflect.Descriptor instead.
func (*GatewayInsertResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GatewayInsertResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type GatewayDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *GatewayKey            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayDeleteRequest) Reset() {
	*x = GatewayDeleteRequest{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayDeleteRequest) ProtoMessage() {}

func (x *GatewayDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayDeleteRequest.ProtoReflect.Descriptor instead.
func (*GatewayDeleteRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GatewayDeleteRequest) GetKey() *GatewayKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GatewayDeleteRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type GatewayDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayDeleteResponse) Reset() {
	*x = GatewayDeleteResponse{}
	mi := &file_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayDeleteResponse) ProtoMessage() {}

func (x *GatewayDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayDeleteResponse.ProtoReflect.Descriptor instead.
func (*GatewayDeleteResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *GatewayDeleteResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\x17vectorsearch.gateway.v1\"?\n" +
	"\n" +
	"GatewayKey\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\x04R\x05label\"h\n" +
	"\x13GatewayScoredResult\x125\n" +
	"\x03key\x18\x01 \x01(\v2#.vectorsearch.gateway.v1.GatewayKeyR\x03key\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\"\x8a\x01\n" +
	"\x14GatewaySearchRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\f\n" +
	"\x01k\x18\x02 \x01(\rR\x01k\x12\x0e\n" +
	"\x02ef\x18\x03 \x01(\rR\x02ef\x12#\n" +
	"\rallow_partial\x18\x04 \x01(\bR\fallowPartial\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\x04R\bclientId\"\xab\x01\n" +
	"\x15GatewaySearchResponse\x12F\n" +
	"\aresults\x18\x01 \x03(\v2,.vectorsearch.gateway.v1.GatewayScoredResultR\aresults\x12%\n" +
	"\x0eshards_queried\x18\x02 \x01(\rR\rshardsQueried\x12#\n" +
	"\rshards_failed\x18\x03 \x01(\rR\fshardsFailed\"\x88\x01\n" +
	"\x14GatewayInsertRequest\x125\n" +
	"\x03key\x18\x01 \x01(\v2#.vectorsearch.gateway.v1.GatewayKeyR\x03key\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\">\n" +
	"\x15GatewayInsertResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\"t\n" +
	"\x14GatewayDeleteRequest\x125\n" +
	"\x03key\x18\x01 \x01(\v2#.vectorsearch.gateway.v1.GatewayKeyR\x03key\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\">\n" +
	"\x15GatewayDeleteResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId2\xc4\x02\n" +
	"\aGateway\x12g\n" +
	"\x06Insert\x12-.vectorsearch.gateway.v1.GatewayInsertRequest\x1a..vectorsearch.gateway.v1.GatewayInsertResponse\x12g\n" +
	"\x06Search\x12-.vectorsearch.gateway.v1.GatewaySearchRequest\x1a..vectorsearch.gateway.v1.GatewaySearchResponse\x12g\n" +
	"\x06Delete\x12-.vectorsearch.gateway.v1.GatewayDeleteRequest\x1a..vectorsearch.gateway.v1.GatewayDeleteResponseBJZHgithub.com/Razeefshaik/vectorsearch-gateway/go/proto/gatewaypb;gatewaypbb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gateway_proto_goTypes = []any{
	(*GatewayKey)(nil),            // 0: vectorsearch.gateway.v1.GatewayKey
	(*GatewayScoredResult)(nil),   // 1: vectorsearch.gateway.v1.GatewayScoredResult
	(*GatewaySearchRequest)(nil),  // 2: vectorsearch.gateway.v1.GatewaySearchRequest
	(*GatewaySearchResponse)(nil), // 3: vectorsearch.gateway.v1.GatewaySearchResponse
	(*GatewayInsertRequest)(nil),  // 4: vectorsearch.gateway.v1.GatewayInsertRequest
	(*GatewayInsertResponse)(nil), // 5: vectorsearch.gateway.v1.GatewayInsertResponse
	(*GatewayDeleteRequest)(nil),  // 6: vectorsearch.gateway.v1.GatewayDeleteRequest
	(*GatewayDeleteResponse)(nil), // 7: vectorsearch.gateway.v1.GatewayDeleteResponse
}
var file_gateway_proto_depIdxs = []int32{
	0, // 0: vectorsearch.gateway.v1.GatewayScoredResult.key:type_name -> vectorsearch.gateway.v1.GatewayKey
	1, // 1: vectorsearch.gateway.v1.GatewaySearchResponse.results:type_name -> vectorsearch.gateway.v1.GatewayScoredResult
	0, // 2: vectorsearch.gateway.v1.GatewayInsertRequest.key:type_name -> vectorsearch.gateway.v1.GatewayKey
	0, // 3: vectorsearch.gateway.v1.GatewayDeleteRequest.key:type_name -> vectorsearch.gateway.v1.GatewayKey
	4, // 4: vectorsearch.gateway.v1.Gateway.Insert:input_type -> vectorsearch.gateway.v1.GatewayInsertRequest
	2, // 5: vectorsearch.gateway.v1.Gateway.Search:input_type -> vectorsearch.gateway.v1.GatewaySearchRequest
	6, // 6: vectorsearch.gateway.v1.Gateway.Delete:input_type -> vectorsearch.gateway.v1.GatewayDeleteRequest
	5, // 7: vectorsearch.gateway.v1.Gateway.Insert:output_type -> vectorsearch.gateway.v1.GatewayInsertResponse
	3, // 8: vectorsearch.gateway.v1.Gateway.Search:output_type -> vectorsearch.gateway.v1.GatewaySearchResponse
	7, // 9: vectorsearch.gateway.v1.Gateway.Delete:output_type -> vectorsearch.gateway.v1.GatewayDeleteResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
