// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: gateway.proto

package gatewaypb

import (
	coordinatorpb "github.com/Razeefshaik/vectorsearch-gateway/go/proto/coordinatorpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewaySearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	K             uint32                 `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	Ef            uint32                 `protobuf:"varint,3,opt,name=ef,proto3" json:"ef,omitempty"`
	AllowPartial  bool                   `protobuf:"varint,4,opt,name=allow_partial,json=allowPartial,proto3" json:"allow_partial,omitempty"`
	ClientId      uint64                 `protobuf:"varint,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewaySearchRequest) Reset() {
	*x = GatewaySearchRequest{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewaySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewaySearchRequest) ProtoMessage() {}

func (x *GatewaySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewaySearchRequest.ProtoReflect.Descriptor instead.
func (*GatewaySearchRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewaySearchRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GatewaySearchRequest) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *GatewaySearchRequest) GetEf() uint32 {
	if x != nil {
		return x.Ef
	}
	return 0
}

func (x *GatewaySearchRequest) GetAllowPartial() bool {
	if x != nil {
		return x.AllowPartial
	}
	return false
}

func (x *GatewaySearchRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GatewayInsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *coordinatorpb.Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayInsertRequest) Reset() {
	*x = GatewayInsertRequest{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayInsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayInsertRequest) ProtoMessage() {}

func (x *GatewayInsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayInsertRequest.ProtoReflect.Descriptor instead.
func (*GatewayInsertRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayInsertRequest) GetKey() *coordinatorpb.Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GatewayInsertRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GatewayInsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayInsertResponse) Reset() {
	*x = GatewayInsertResponse{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayInsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayInsertResponse) ProtoMessage() {}

func (x *GatewayInsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayInsertResponse.ProtoReflect.Descriptor instead.
func (*GatewayInsertResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\x17vectorsearch.gateway.v1\x1a\x11coordinator.proto\"\x8a\x01\n" +
	"\x14GatewaySearchRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\f\n" +
	"\x01k\x18\x02 \x01(\rR\x01k\x12\x0e\n" +
	"\x02ef\x18\x03 \x01(\rR\x02ef\x12#\n" +
	"\rallow_partial\x18\x04 \x01(\bR\fallowPartial\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\x04R\bclientId\"^\n" +
	"\x14GatewayInsertRequest\x122\n" +
	"\x03key\x18\x01 \x01(\v2 .vectorsearch.coordinator.v1.KeyR\x03key\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x17\n" +
	"\x15GatewayInsertResponse2\xbb\x02\n" +
	"\aGateway\x12g\n" +
	"\x06Insert\x12-.vectorsearch.gateway.v1.GatewayInsertRequest\x1a..vectorsearch.gateway.v1.GatewayInsertResponse\x12d\n" +
	"\x06Search\x12-.vectorsearch.gateway.v1.GatewaySearchRequest\x1a+.vectorsearch.coordinator.v1.SearchResponse\x12a\n" +
	"\x06Delete\x12*.vectorsearch.coordinator.v1.DeleteRequest\x1a+.vectorsearch.coordinator.v1.DeleteResponseBJZHgithub.com/Razeefshaik/vectorsearch-gateway/go/proto/gatewaypb;gatewaypbb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_proto_goTypes = []any{
	(*GatewaySearchRequest)(nil),         // 0: vectorsearch.gateway.v1.GatewaySearchRequest
	(*GatewayInsertRequest)(nil),         // 1: vectorsearch.gateway.v1.GatewayInsertRequest
	(*GatewayInsertResponse)(nil),        // 2: vectorsearch.gateway.v1.GatewayInsertResponse
	(*coordinatorpb.Key)(nil),            // 3: vectorsearch.coordinator.v1.Key
	(*coordinatorpb.DeleteRequest)(nil),  // 4: vectorsearch.coordinator.v1.DeleteRequest
	(*coordinatorpb.SearchResponse)(nil), // 5: vectorsearch.coordinator.v1.SearchResponse
	(*coordinatorpb.DeleteResponse)(nil), // 6: vectorsearch.coordinator.v1.DeleteResponse
}
var file_gateway_proto_depIdxs = []int32{
	3, // 0: vectorsearch.gateway.v1.GatewayInsertRequest.key:type_name -> vectorsearch.coordinator.v1.Key
	1, // 1: vectorsearch.gateway.v1.Gateway.Insert:input_type -> vectorsearch.gateway.v1.GatewayInsertRequest
	0, // 2: vectorsearch.gateway.v1.Gateway.Search:input_type -> vectorsearch.gateway.v1.GatewaySearchRequest
	4, // 3: vectorsearch.gateway.v1.Gateway.Delete:input_type -> vectorsearch.coordinator.v1.DeleteRequest
	2, // 4: vectorsearch.gateway.v1.Gateway.Insert:output_type -> vectorsearch.gateway.v1.GatewayInsertResponse
	5, // 5: vectorsearch.gateway.v1.Gateway.Search:output_type -> vectorsearch.coordinator.v1.SearchResponse
	6, // 6: vectorsearch.gateway.v1.Gateway.Delete:output_type -> vectorsearch.coordinator.v1.DeleteResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
